const generateRandomTsCode = () => {
  const code = `// Generated by https://github.com/nandanjones/CodingProject
import { useState } from 'react';

function MyComponent() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>Count: {count}</p>
      <button onClick={() => setCount(count + 1)}>Increment</button>
    </div>
  );
}

export default MyComponent;
`;

return code;
};
